#############################################################################
# Makefile for building: ukui-panel
# Generated by qmake (3.1) (Qt 5.12.2)
# Project:  ukui-panel.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile ukui-panel.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/lxqt -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/qt5xdg -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/KF5 -isystem /usr/include/KF5/KWindowSystem -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/KF5/KWindowSystem -isystem /usr/include/lxqt-globalkeys -isystem /usr/include/lxqt/LXQt -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ukui-panel1.0.0
DISTDIR = /home/hepuyao/下载/0822/ukui-panel-master/.tmp/ukui-panel1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lKF5WindowSystem -llxqt -lQt5X11Extras -lQt5Xdg -lQt5Widgets -lQt5Gui -lQt5Core /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ukuipanelapplication.cpp \
		ukuipanel.cpp \
		panelpluginsmodel.cpp \
		plugin.cpp \
		pluginsettings.cpp \
		ukuimenu.cpp \
		config/addplugindialog.cpp \
		config/configpaneldialog.cpp \
		config/configpanelwidget.cpp \
		config/configpluginswidget.cpp \
		windownotifier.cpp \
		plugin-desktopswitch/desktopswitch.cpp \
		plugin-desktopswitch/desktopswitchbutton.cpp \
		plugin-desktopswitch/desktopswitchconfiguration.cpp \
		lxqtpanelpluginconfigdialog.cpp \
		panel/ukuipanellayout.cpp \
		ukuipluginmoveprocessor.cpp moc_ukuipanelapplication.cpp \
		moc_ukuipanel.cpp \
		moc_panelpluginsmodel.cpp \
		moc_plugin.cpp \
		moc_addplugindialog.cpp \
		moc_configpaneldialog.cpp \
		moc_configpanelwidget.cpp \
		moc_configpluginswidget.cpp \
		moc_windownotifier.cpp \
		moc_desktopswitch.cpp \
		moc_desktopswitchbutton.cpp \
		moc_desktopswitchconfiguration.cpp \
		moc_lxqtpanelpluginconfigdialog.cpp \
		moc_ukuipanellayout.cpp \
		moc_ukuipluginmoveprocessor.cpp
OBJECTS       = main.o \
		ukuipanelapplication.o \
		ukuipanel.o \
		panelpluginsmodel.o \
		plugin.o \
		pluginsettings.o \
		ukuimenu.o \
		addplugindialog.o \
		configpaneldialog.o \
		configpanelwidget.o \
		configpluginswidget.o \
		windownotifier.o \
		desktopswitch.o \
		desktopswitchbutton.o \
		desktopswitchconfiguration.o \
		lxqtpanelpluginconfigdialog.o \
		ukuipanellayout.o \
		ukuipluginmoveprocessor.o \
		moc_ukuipanelapplication.o \
		moc_ukuipanel.o \
		moc_panelpluginsmodel.o \
		moc_plugin.o \
		moc_addplugindialog.o \
		moc_configpaneldialog.o \
		moc_configpanelwidget.o \
		moc_configpluginswidget.o \
		moc_windownotifier.o \
		moc_desktopswitch.o \
		moc_desktopswitchbutton.o \
		moc_desktopswitchconfiguration.o \
		moc_lxqtpanelpluginconfigdialog.o \
		moc_ukuipanellayout.o \
		moc_ukuipluginmoveprocessor.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ukui-panel.pro ukuipanelapplication.h \
		ukuipanel.h \
		panelpluginsmodel.h \
		plugin.h \
		pluginsettings.h \
		ukuimenu.h \
		config/addplugindialog.h \
		config/configpaneldialog.h \
		config/configpanelwidget.h \
		config/configpluginswidget.h \
		windownotifier.h \
		plugin-desktopswitch/desktopswitch.h \
		plugin-desktopswitch/desktopswitchbutton.h \
		plugin-desktopswitch/desktopswitchconfiguration.h \
		lxqtpanelpluginconfigdialog.h \
		panel/ukuipanellayout.h \
		ukuipluginmoveprocessor.h main.cpp \
		ukuipanelapplication.cpp \
		ukuipanel.cpp \
		panelpluginsmodel.cpp \
		plugin.cpp \
		pluginsettings.cpp \
		ukuimenu.cpp \
		config/addplugindialog.cpp \
		config/configpaneldialog.cpp \
		config/configpanelwidget.cpp \
		config/configpluginswidget.cpp \
		windownotifier.cpp \
		plugin-desktopswitch/desktopswitch.cpp \
		plugin-desktopswitch/desktopswitchbutton.cpp \
		plugin-desktopswitch/desktopswitchconfiguration.cpp \
		lxqtpanelpluginconfigdialog.cpp \
		panel/ukuipanellayout.cpp \
		ukuipluginmoveprocessor.cpp
QMAKE_TARGET  = ukui-panel
DESTDIR       = 
TARGET        = ukui-panel


first: all
####### Build rules

ukui-panel: ui_addplugindialog.h ui_configpanelwidget.h ui_configpluginswidget.h ui_desktopswitchconfiguration.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ukui-panel.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ukui-panel.pro \
		/usr/lib/x86_64-linux-gnu/libQt5X11Extras.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile ukui-panel.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
ukui-panel.pro:
/usr/lib/x86_64-linux-gnu/libQt5X11Extras.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ukui-panel.pro

qmake_all: FORCE


all: Makefile ukui-panel

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ukuipanelapplication.h ukuipanel.h panelpluginsmodel.h plugin.h pluginsettings.h ukuimenu.h config/addplugindialog.h config/configpaneldialog.h config/configpanelwidget.h config/configpluginswidget.h windownotifier.h plugin-desktopswitch/desktopswitch.h plugin-desktopswitch/desktopswitchbutton.h plugin-desktopswitch/desktopswitchconfiguration.h lxqtpanelpluginconfigdialog.h panel/ukuipanellayout.h ukuipluginmoveprocessor.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp ukuipanelapplication.cpp ukuipanel.cpp panelpluginsmodel.cpp plugin.cpp pluginsettings.cpp ukuimenu.cpp config/addplugindialog.cpp config/configpaneldialog.cpp config/configpanelwidget.cpp config/configpluginswidget.cpp windownotifier.cpp plugin-desktopswitch/desktopswitch.cpp plugin-desktopswitch/desktopswitchbutton.cpp plugin-desktopswitch/desktopswitchconfiguration.cpp lxqtpanelpluginconfigdialog.cpp panel/ukuipanellayout.cpp ukuipluginmoveprocessor.cpp $(DISTDIR)/
	$(COPY_FILE) --parents config/addplugindialog.ui config/configpanelwidget.ui config/configpluginswidget.ui plugin-desktopswitch/desktopswitchconfiguration.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_ukuipanelapplication.cpp moc_ukuipanel.cpp moc_panelpluginsmodel.cpp moc_plugin.cpp moc_addplugindialog.cpp moc_configpaneldialog.cpp moc_configpanelwidget.cpp moc_configpluginswidget.cpp moc_windownotifier.cpp moc_desktopswitch.cpp moc_desktopswitchbutton.cpp moc_desktopswitchconfiguration.cpp moc_lxqtpanelpluginconfigdialog.cpp moc_ukuipanellayout.cpp moc_ukuipluginmoveprocessor.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ukuipanelapplication.cpp moc_ukuipanel.cpp moc_panelpluginsmodel.cpp moc_plugin.cpp moc_addplugindialog.cpp moc_configpaneldialog.cpp moc_configpanelwidget.cpp moc_configpluginswidget.cpp moc_windownotifier.cpp moc_desktopswitch.cpp moc_desktopswitchbutton.cpp moc_desktopswitchconfiguration.cpp moc_lxqtpanelpluginconfigdialog.cpp moc_ukuipanellayout.cpp moc_ukuipluginmoveprocessor.cpp
moc_ukuipanelapplication.cpp: ukuipanelapplication.h \
		ilxqtpanel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hepuyao/下载/0822/ukui-panel-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hepuyao/下载/0822/ukui-panel-master -I/home/hepuyao/下载/0822/ukui-panel-master -I/usr/include/lxqt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/qt5xdg -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5 -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/KF5/KWindowSystem -I/usr/include/lxqt-globalkeys -I/usr/include/lxqt/LXQt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ukuipanelapplication.h -o moc_ukuipanelapplication.cpp

moc_ukuipanel.cpp: ukuipanel.h \
		panelpluginsmodel.h \
		ukuipanel.h \
		ilxqtpanel.h \
		panel/ukuipanellayout.h \
		plugin.h \
		pluginsettings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hepuyao/下载/0822/ukui-panel-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hepuyao/下载/0822/ukui-panel-master -I/home/hepuyao/下载/0822/ukui-panel-master -I/usr/include/lxqt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/qt5xdg -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5 -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/KF5/KWindowSystem -I/usr/include/lxqt-globalkeys -I/usr/include/lxqt/LXQt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ukuipanel.h -o moc_ukuipanel.cpp

moc_panelpluginsmodel.cpp: panelpluginsmodel.h \
		ukuipanel.h \
		panelpluginsmodel.h \
		plugin.h \
		pluginsettings.h \
		ilxqtpanel.h \
		panel/ukuipanellayout.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hepuyao/下载/0822/ukui-panel-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hepuyao/下载/0822/ukui-panel-master -I/home/hepuyao/下载/0822/ukui-panel-master -I/usr/include/lxqt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/qt5xdg -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5 -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/KF5/KWindowSystem -I/usr/include/lxqt-globalkeys -I/usr/include/lxqt/LXQt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include panelpluginsmodel.h -o moc_panelpluginsmodel.cpp

moc_plugin.cpp: plugin.h \
		ukuipanel.h \
		panelpluginsmodel.h \
		plugin.h \
		pluginsettings.h \
		ilxqtpanel.h \
		panel/ukuipanellayout.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hepuyao/下载/0822/ukui-panel-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hepuyao/下载/0822/ukui-panel-master -I/home/hepuyao/下载/0822/ukui-panel-master -I/usr/include/lxqt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/qt5xdg -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5 -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/KF5/KWindowSystem -I/usr/include/lxqt-globalkeys -I/usr/include/lxqt/LXQt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include plugin.h -o moc_plugin.cpp

moc_addplugindialog.cpp: config/addplugindialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hepuyao/下载/0822/ukui-panel-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hepuyao/下载/0822/ukui-panel-master -I/home/hepuyao/下载/0822/ukui-panel-master -I/usr/include/lxqt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/qt5xdg -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5 -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/KF5/KWindowSystem -I/usr/include/lxqt-globalkeys -I/usr/include/lxqt/LXQt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include config/addplugindialog.h -o moc_addplugindialog.cpp

moc_configpaneldialog.cpp: config/configpaneldialog.h \
		config/configpanelwidget.h \
		ukuipanel.h \
		panelpluginsmodel.h \
		plugin.h \
		pluginsettings.h \
		ilxqtpanel.h \
		panel/ukuipanellayout.h \
		config/configpluginswidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hepuyao/下载/0822/ukui-panel-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hepuyao/下载/0822/ukui-panel-master -I/home/hepuyao/下载/0822/ukui-panel-master -I/usr/include/lxqt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/qt5xdg -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5 -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/KF5/KWindowSystem -I/usr/include/lxqt-globalkeys -I/usr/include/lxqt/LXQt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include config/configpaneldialog.h -o moc_configpaneldialog.cpp

moc_configpanelwidget.cpp: config/configpanelwidget.h \
		ukuipanel.h \
		panelpluginsmodel.h \
		plugin.h \
		pluginsettings.h \
		ilxqtpanel.h \
		panel/ukuipanellayout.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hepuyao/下载/0822/ukui-panel-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hepuyao/下载/0822/ukui-panel-master -I/home/hepuyao/下载/0822/ukui-panel-master -I/usr/include/lxqt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/qt5xdg -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5 -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/KF5/KWindowSystem -I/usr/include/lxqt-globalkeys -I/usr/include/lxqt/LXQt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include config/configpanelwidget.h -o moc_configpanelwidget.cpp

moc_configpluginswidget.cpp: config/configpluginswidget.h \
		ukuipanel.h \
		panelpluginsmodel.h \
		plugin.h \
		pluginsettings.h \
		ilxqtpanel.h \
		panel/ukuipanellayout.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hepuyao/下载/0822/ukui-panel-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hepuyao/下载/0822/ukui-panel-master -I/home/hepuyao/下载/0822/ukui-panel-master -I/usr/include/lxqt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/qt5xdg -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5 -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/KF5/KWindowSystem -I/usr/include/lxqt-globalkeys -I/usr/include/lxqt/LXQt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include config/configpluginswidget.h -o moc_configpluginswidget.cpp

moc_windownotifier.cpp: windownotifier.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hepuyao/下载/0822/ukui-panel-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hepuyao/下载/0822/ukui-panel-master -I/home/hepuyao/下载/0822/ukui-panel-master -I/usr/include/lxqt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/qt5xdg -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5 -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/KF5/KWindowSystem -I/usr/include/lxqt-globalkeys -I/usr/include/lxqt/LXQt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include windownotifier.h -o moc_windownotifier.cpp

moc_desktopswitch.cpp: plugin-desktopswitch/desktopswitch.h \
		panel/ilxqtpanelplugin.h \
		ilxqtpanel.h \
		plugin-desktopswitch/desktopswitchbutton.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hepuyao/下载/0822/ukui-panel-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hepuyao/下载/0822/ukui-panel-master -I/home/hepuyao/下载/0822/ukui-panel-master -I/usr/include/lxqt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/qt5xdg -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5 -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/KF5/KWindowSystem -I/usr/include/lxqt-globalkeys -I/usr/include/lxqt/LXQt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include plugin-desktopswitch/desktopswitch.h -o moc_desktopswitch.cpp

moc_desktopswitchbutton.cpp: plugin-desktopswitch/desktopswitchbutton.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hepuyao/下载/0822/ukui-panel-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hepuyao/下载/0822/ukui-panel-master -I/home/hepuyao/下载/0822/ukui-panel-master -I/usr/include/lxqt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/qt5xdg -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5 -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/KF5/KWindowSystem -I/usr/include/lxqt-globalkeys -I/usr/include/lxqt/LXQt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include plugin-desktopswitch/desktopswitchbutton.h -o moc_desktopswitchbutton.cpp

moc_desktopswitchconfiguration.cpp: plugin-desktopswitch/desktopswitchconfiguration.h \
		lxqtpanelpluginconfigdialog.h \
		pluginsettings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hepuyao/下载/0822/ukui-panel-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hepuyao/下载/0822/ukui-panel-master -I/home/hepuyao/下载/0822/ukui-panel-master -I/usr/include/lxqt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/qt5xdg -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5 -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/KF5/KWindowSystem -I/usr/include/lxqt-globalkeys -I/usr/include/lxqt/LXQt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include plugin-desktopswitch/desktopswitchconfiguration.h -o moc_desktopswitchconfiguration.cpp

moc_lxqtpanelpluginconfigdialog.cpp: lxqtpanelpluginconfigdialog.h \
		pluginsettings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hepuyao/下载/0822/ukui-panel-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hepuyao/下载/0822/ukui-panel-master -I/home/hepuyao/下载/0822/ukui-panel-master -I/usr/include/lxqt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/qt5xdg -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5 -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/KF5/KWindowSystem -I/usr/include/lxqt-globalkeys -I/usr/include/lxqt/LXQt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include lxqtpanelpluginconfigdialog.h -o moc_lxqtpanelpluginconfigdialog.cpp

moc_ukuipanellayout.cpp: panel/ukuipanellayout.h \
		ilxqtpanel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hepuyao/下载/0822/ukui-panel-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hepuyao/下载/0822/ukui-panel-master -I/home/hepuyao/下载/0822/ukui-panel-master -I/usr/include/lxqt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/qt5xdg -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5 -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/KF5/KWindowSystem -I/usr/include/lxqt-globalkeys -I/usr/include/lxqt/LXQt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include panel/ukuipanellayout.h -o moc_ukuipanellayout.cpp

moc_ukuipluginmoveprocessor.cpp: ukuipluginmoveprocessor.h \
		plugin.h \
		ukuipanel.h \
		panelpluginsmodel.h \
		ilxqtpanel.h \
		panel/ukuipanellayout.h \
		pluginsettings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hepuyao/下载/0822/ukui-panel-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hepuyao/下载/0822/ukui-panel-master -I/home/hepuyao/下载/0822/ukui-panel-master -I/usr/include/lxqt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/qt5xdg -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5 -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/KF5/KWindowSystem -I/usr/include/lxqt-globalkeys -I/usr/include/lxqt/LXQt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ukuipluginmoveprocessor.h -o moc_ukuipluginmoveprocessor.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_addplugindialog.h ui_configpanelwidget.h ui_configpluginswidget.h ui_desktopswitchconfiguration.h
compiler_uic_clean:
	-$(DEL_FILE) ui_addplugindialog.h ui_configpanelwidget.h ui_configpluginswidget.h ui_desktopswitchconfiguration.h
ui_addplugindialog.h: config/addplugindialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic config/addplugindialog.ui -o ui_addplugindialog.h

ui_configpanelwidget.h: config/configpanelwidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic config/configpanelwidget.ui -o ui_configpanelwidget.h

ui_configpluginswidget.h: config/configpluginswidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic config/configpluginswidget.ui -o ui_configpluginswidget.h

ui_desktopswitchconfiguration.h: plugin-desktopswitch/desktopswitchconfiguration.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic plugin-desktopswitch/desktopswitchconfiguration.ui -o ui_desktopswitchconfiguration.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ukuipanelapplication.h \
		ilxqtpanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ukuipanelapplication.o: ukuipanelapplication.cpp ukuipanelapplication.h \
		ilxqtpanel.h \
		ukuipanel.h \
		panelpluginsmodel.h \
		plugin.h \
		pluginsettings.h \
		panel/ukuipanellayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukuipanelapplication.o ukuipanelapplication.cpp

ukuipanel.o: ukuipanel.cpp ukuipanel.h \
		panelpluginsmodel.h \
		plugin.h \
		pluginsettings.h \
		ilxqtpanel.h \
		panel/ukuipanellayout.h \
		windownotifier.h \
		ukuipanelapplication.h \
		ukuimenu.h \
		config/configpaneldialog.h \
		config/configpanelwidget.h \
		config/configpluginswidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukuipanel.o ukuipanel.cpp

panelpluginsmodel.o: panelpluginsmodel.cpp panelpluginsmodel.h \
		ukuipanel.h \
		ilxqtpanel.h \
		panel/ukuipanellayout.h \
		plugin.h \
		pluginsettings.h \
		ukuipanelapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o panelpluginsmodel.o panelpluginsmodel.cpp

plugin.o: plugin.cpp plugin.h \
		ukuipanel.h \
		panelpluginsmodel.h \
		ilxqtpanel.h \
		panel/ukuipanellayout.h \
		pluginsettings.h \
		plugin-desktopswitch/desktopswitch.h \
		panel/ilxqtpanelplugin.h \
		plugin-desktopswitch/desktopswitchbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plugin.o plugin.cpp

pluginsettings.o: pluginsettings.cpp pluginsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pluginsettings.o pluginsettings.cpp

ukuimenu.o: ukuimenu.cpp ukuimenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukuimenu.o ukuimenu.cpp

addplugindialog.o: config/addplugindialog.cpp ui_addplugindialog.h \
		config/addplugindialog.h \
		plugin.h \
		ukuipanel.h \
		panelpluginsmodel.h \
		ilxqtpanel.h \
		panel/ukuipanellayout.h \
		pluginsettings.h \
		ukuipanelapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addplugindialog.o config/addplugindialog.cpp

configpaneldialog.o: config/configpaneldialog.cpp config/configpaneldialog.h \
		config/configpanelwidget.h \
		ukuipanel.h \
		panelpluginsmodel.h \
		plugin.h \
		pluginsettings.h \
		ilxqtpanel.h \
		panel/ukuipanellayout.h \
		config/configpluginswidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configpaneldialog.o config/configpaneldialog.cpp

configpanelwidget.o: config/configpanelwidget.cpp config/configpanelwidget.h \
		ukuipanel.h \
		panelpluginsmodel.h \
		plugin.h \
		pluginsettings.h \
		ilxqtpanel.h \
		panel/ukuipanellayout.h \
		ui_configpanelwidget.h \
		panel/lxqtpanellimits.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configpanelwidget.o config/configpanelwidget.cpp

configpluginswidget.o: config/configpluginswidget.cpp config/configpluginswidget.h \
		ukuipanel.h \
		panelpluginsmodel.h \
		plugin.h \
		pluginsettings.h \
		ilxqtpanel.h \
		panel/ukuipanellayout.h \
		ui_configpluginswidget.h \
		config/addplugindialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configpluginswidget.o config/configpluginswidget.cpp

windownotifier.o: windownotifier.cpp windownotifier.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o windownotifier.o windownotifier.cpp

desktopswitch.o: plugin-desktopswitch/desktopswitch.cpp plugin-desktopswitch/desktopswitch.h \
		panel/ilxqtpanelplugin.h \
		ilxqtpanel.h \
		plugin-desktopswitch/desktopswitchbutton.h \
		plugin-desktopswitch/desktopswitchconfiguration.h \
		lxqtpanelpluginconfigdialog.h \
		pluginsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o desktopswitch.o plugin-desktopswitch/desktopswitch.cpp

desktopswitchbutton.o: plugin-desktopswitch/desktopswitchbutton.cpp plugin-desktopswitch/desktopswitchbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o desktopswitchbutton.o plugin-desktopswitch/desktopswitchbutton.cpp

desktopswitchconfiguration.o: plugin-desktopswitch/desktopswitchconfiguration.cpp plugin-desktopswitch/desktopswitchconfiguration.h \
		lxqtpanelpluginconfigdialog.h \
		pluginsettings.h \
		ui_desktopswitchconfiguration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o desktopswitchconfiguration.o plugin-desktopswitch/desktopswitchconfiguration.cpp

lxqtpanelpluginconfigdialog.o: lxqtpanelpluginconfigdialog.cpp lxqtpanelpluginconfigdialog.h \
		pluginsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lxqtpanelpluginconfigdialog.o lxqtpanelpluginconfigdialog.cpp

ukuipanellayout.o: panel/ukuipanellayout.cpp panel/ukuipanellayout.h \
		ilxqtpanel.h \
		plugin.h \
		ukuipanel.h \
		panelpluginsmodel.h \
		pluginsettings.h \
		panel/lxqtpanellimits.h \
		panel/ilxqtpanelplugin.h \
		ukuipluginmoveprocessor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukuipanellayout.o panel/ukuipanellayout.cpp

ukuipluginmoveprocessor.o: ukuipluginmoveprocessor.cpp ukuipluginmoveprocessor.h \
		plugin.h \
		ukuipanel.h \
		panelpluginsmodel.h \
		ilxqtpanel.h \
		panel/ukuipanellayout.h \
		pluginsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukuipluginmoveprocessor.o ukuipluginmoveprocessor.cpp

moc_ukuipanelapplication.o: moc_ukuipanelapplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukuipanelapplication.o moc_ukuipanelapplication.cpp

moc_ukuipanel.o: moc_ukuipanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukuipanel.o moc_ukuipanel.cpp

moc_panelpluginsmodel.o: moc_panelpluginsmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_panelpluginsmodel.o moc_panelpluginsmodel.cpp

moc_plugin.o: moc_plugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_plugin.o moc_plugin.cpp

moc_addplugindialog.o: moc_addplugindialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addplugindialog.o moc_addplugindialog.cpp

moc_configpaneldialog.o: moc_configpaneldialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configpaneldialog.o moc_configpaneldialog.cpp

moc_configpanelwidget.o: moc_configpanelwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configpanelwidget.o moc_configpanelwidget.cpp

moc_configpluginswidget.o: moc_configpluginswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configpluginswidget.o moc_configpluginswidget.cpp

moc_windownotifier.o: moc_windownotifier.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_windownotifier.o moc_windownotifier.cpp

moc_desktopswitch.o: moc_desktopswitch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_desktopswitch.o moc_desktopswitch.cpp

moc_desktopswitchbutton.o: moc_desktopswitchbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_desktopswitchbutton.o moc_desktopswitchbutton.cpp

moc_desktopswitchconfiguration.o: moc_desktopswitchconfiguration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_desktopswitchconfiguration.o moc_desktopswitchconfiguration.cpp

moc_lxqtpanelpluginconfigdialog.o: moc_lxqtpanelpluginconfigdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lxqtpanelpluginconfigdialog.o moc_lxqtpanelpluginconfigdialog.cpp

moc_ukuipanellayout.o: moc_ukuipanellayout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukuipanellayout.o moc_ukuipanellayout.cpp

moc_ukuipluginmoveprocessor.o: moc_ukuipluginmoveprocessor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukuipluginmoveprocessor.o moc_ukuipluginmoveprocessor.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

